# Generated by Django 4.1.7 on 2023-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_pic', models.ImageField(default='pics/default_place.png', upload_to='pics')),
                ('place_region', models.CharField(blank=True, max_length=50, null=True)),
                ('place_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('place_desc', models.TextField()),
                ('place_alias', models.TextField()),
                ('related_pics', models.FileField(default='null', upload_to='relatedpics')),
            ],
        ),
    ]
