# Generated by Django 4.1.7 on 2023-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='gmail_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
