# Generated by Django 4.1.7 on 2023-04-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_contactus_gmail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='gmail_password',
        ),
    ]
