# Generated by Django 4.1.7 on 2023-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_contactus_gmail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_available',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
